name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Yarn
        run: npm install -g @yarnpkg/cli-dist@4.9.2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Lint
        run: yarn lint

  a11y:
    name: Accessibility Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Yarn
        run: npm install -g @yarnpkg/cli-dist@4.9.2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Accessibility Audit
        run: yarn a11y
